GET http://localhost:8080

###

GET http://localhost:8080/categories

###

POST http://localhost:8080/categories
Content-Type: application/json

{ "title": "brico" }

###

PATCH http://localhost:8080/categories/61307c3792357d097150b1ab
Content-Type: application/json

{ "title": "brico test" }

###

GET http://localhost:8080/articles

###

POST http://localhost:8080/articles
Content-Type: application/json

{
  "title": "Mon premier article",
  "description": "Description",
  "content": "Lorem ipsum"
}
